### ISSUE TITLE
Failed search at official website

### ISSUE THREAD

**Issue by nizzam** [blade-ui-kit/blade-heroicons#46]
### Description:

I tried to search an icon but the page doesn't make searching at all.

Here the url : https://blade-ui-kit.com/blade-icons#search

Thank you

**Comment by driesvints** [comment]
Fixed, thanks!

**Comment by nizzam** [comment]
Do you mind to recheck again. Still cant perform a searching. I tried on several browsers but still failed.

**Comment by driesvints** [comment]
I don't know what to say. It's works fine for me:

<img width="1512" alt="Screenshot 2024-02-19 at 10 53 44" src="https://github.com/blade-ui-kit/blade-heroicons/assets/594614/20550f4b-cfdb-4aa9-8b7e-f81fea1643fa">

**Comment by nizzam** [comment]
Working well now.
Thank you for the follow-up 👍
